import { state } from './state.js';
import { initEditor } from './editor.js';
import { initTools } from './tools.js';
import { initLayers } from './layers.js';
import { initFilters } from './filters.js';
import { initPresets } from './presets.js';
import { initTemplates } from './templates.js';
import { initExport } from './export.js';
import { initVideoSource } from './video-source.js';
import { initFrameCapture } from './frame-capture.js';

initEditor();
initTools();
initLayers();
initFilters();
initPresets();
initTemplates();
initExport();
initVideoSource();
initFrameCapture();
